### ISSUE TITLE
How to use RAT

### ISSUE THREAD

**Issue by Inge-van-Vugt** [MGXlab/CAT_pack#110]
Hi,

I was wondering how I can use RAT. In the README their is information about RAT but the newest version doesn't contain RAT. 

Thanks and kind regards,

Inge

**Comment by bastiaanvonmeijenfeldt** [comment]
Hi @Inge-van-Vugt,

The current version of CAT (from v6.0 onwards) now includes RAT! We hope you like it.
Let us know how it goes!

Best wishes,

Bastiaan
