### ISSUE TITLE
Error in RAT (CAT_pack 6.0)

### ISSUE THREAD

**Issue by SrichandanPadhi** [MGXlab/CAT_pack#116]
I was running RAT in CAT_pack v 6.0. following error encountered. Please help me solving the issue.

diamond blastx -d /scratch/srichandanp/CAT_pack/20231120_CAT_nr/db/2023-11-21_CAT.dmnd -q ./out.RAT.unclassified_unmapped.fasta --top 11 --matrix BLOSUM62 --evalue 0.001 -o ./out.RAT.unclassified_unmapped.alignment.diamond -p 48 --block-size 12.0 --index-chunks 1 --tmpdir ./ --compress 0 --quiet
[2024-03-13 20:48:31] Homology search done! File ./out.RAT.unclassified_unmapped.alignment.diamond created.
[2024-03-13 20:48:31] Loading file /scratch/srichandanp/CAT_pack/20231120_CAT_nr/tax/nodes.dmp.
[2024-03-13 20:48:35] Parsing alignment file ./out.RAT.unclassified_unmapped.alignment.diamond.
[2024-03-13 20:55:00] Loading file /scratch/srichandanp/CAT_pack/20231120_CAT_nr/db/2023-11-21_CAT.fastaid2LCAtaxid.
[2024-03-13 20:59:22] Loading file /scratch/srichandanp/CAT_pack/20231120_CAT_nr/db/2023-11-21_CAT.taxids_with_multiple_offspring.
[2024-03-13 20:59:22] Finding lineages for unclassified/unmapped sequences...
[2024-03-13 21:21:35] Loading file /scratch/srichandanp/CAT_pack/20231120_CAT_nr/tax/nodes.dmp.
[2024-03-13 21:21:49] Writing output tables.
Traceback (most recent call last):
  File "/scratch/srichandanp/CAT_pack/CAT_pack-6.0/CAT_pack/CAT_pack", line 101, in <module>
    main()
  File "/scratch/srichandanp/CAT_pack/CAT_pack-6.0/CAT_pack/CAT_pack", line 85, in main
    reads.run()
  File "/scratch/srichandanp/CAT_pack/CAT_pack-6.0/CAT_pack/reads.py", line 511, in run
    make_tax_table(c2c,
  File "/scratch/srichandanp/CAT_pack/CAT_pack-6.0/CAT_pack/reads.py", line 941, in make_tax_table
    taxon_dict[taxon]['n_nucleotides']+=contig_length_dict[contig]
                                        ~~~~~~~~~~~~~~~~~~^^^^^^^^
KeyError: 'k141_210696'

**Comment by thauptfeld** [comment]
Hello!

This happens when the names in the contig file have more than the contig ID in the fasta header, e.g. when the fasta header is:

"contig_1 then_stuff_after contig_id with space between"

One of the functions in RAT saved the entire fasta header instead of just the fasta id. I have uploaded a new reads.py that should fix this issue.

The good news is that you can pick up your run right where it left off by supplying the contig2classification, bin2classification file, and unmapped2classification along with the rest of the arguments and RAT should just load everything and write the output tables.

I hope this helps!
Best,
Tina

**Comment by SrichandanPadhi** [comment]
It works fine and perfect..
Thank you very much, Tina !

**Comment by SrichandanPadhi** [comment]
Another error encountered but this time with "add_names"

Following is the code

/scratch/srichandanp/CAT_pack/CAT_pack-6.0/CAT_pack/CAT_pack add_names -i /scratch/srichandanp/CAT_pack/ST_MNF_P1_S49_rat/out.RAT.complete.abundance.txt -o complete_abundance_with_names.txt -t /scratch/srichandanp/CAT_pack/20231120_CAT_nr/tax/
/scratch/srichandanp/CAT_pack/CAT_pack-6.0/CAT_pack/CAT_pack add_names -i /scratch/srichandanp/CAT_pack/ST_MNF_P1_S49_rat/out.RAT.contig.abundance.txt -o contig_abundance_with_names.txt -t /scratch/srichandanp/CAT_pack/20231120_CAT_nr/tax/
/scratch/srichandanp/CAT_pack/CAT_pack-6.0/CAT_pack/CAT_pack add_names -i /scratch/srichandanp/CAT_pack/ST_MNF_P1_S49_rat/out.RAT.bin.reads.txt -o bin_abundance_with_names.txt -t /scratch/srichandanp/CAT_pack/20231120_CAT_nr/tax/

Following is the error
ERROR: /scratch/srichandanp/CAT_pack/ST_MNF_P1_S49_rat/out.RAT.complete.abundance.txt is not a supported classification file.

Your kind help is deeply appreciated.

**Comment by thauptfeld** [comment]
Hi again!

We actually solved that issue a few days ago! You can do one of two things: you can just download the current add_names.py from github and overwrite yours, or you can change line 87 of script add_names.py from:
`if line.startswith("#"):`
to
`if line.startswith("# "):`
There needs to be a space after the # symbol.

Cheers,
Tina

**Comment by SrichandanPadhi** [comment]
I did the change, but it worked partially that is for contig abundance and complete abundance. How will I add names to the "out.RAT.bin.reads.txt". The moification in script does not work for it and displaying following error message

/out.RAT.bin.reads.txt is not a supported classification file.

Thank you very much for suggestions and corrections

**Comment by thauptfeld** [comment]
This is, because the bin.reads.txt doesn't have the lineages. It only has the length of the bins and the number and fraction of reads mapping to the bin. If you want to see the lineages for the bins, you have to look at the bin2classification file, which should be add_names-able :)

**Comment by SrichandanPadhi** [comment]
It works fine as earlier.
Thank you for the support.
