### ISSUE TITLE
How to pass the diamond parameter (--evalue) to CAT

### ISSUE THREAD

**Issue by zhaoxvwahaha** [MGXlab/CAT_pack#55]
How to pass the diamond parameters ( such as --evalue) to CAT

**Comment by bastiaanvonmeijenfeldt** [comment]
Hi @zhaoxvwahaha,

Currently we only allow tuning some DIAMOND parameters from within CAT and BAT. You will see all DIAMOND parameters that you can change when you run `CAT contigs -h`.
Having said that, you can run the DIAMOND step yourself outside CAT if you have the predicted proteins fasta file and the DIAMOND database inside the CAT database folder. You can find the DIAMOND command that CAT runs [here](https://github.com/dutilh/CAT/blob/master/CAT_pack/shared.py#L667).

`diamond blastp -d $DIAMOND_DATABASE -q $PROTEINS_FASTA --top $TOP --matrix BLOSUM62 --evalue 0.001 -o output.alignment.diamond -p $nproc`

If you do that with your preferred parameters, you'll get an alignment file (in the example above it's called `output.alignment.diamond`. Next, you can run CAT with this alignment file using the the `-a` or `--diamond_alignment` flag. You'll also have to supply the predicted proteins fasta file.

`CAT contigs -c $CONTIGS -a output.alignment.diamond -p $PROTEINS_FASTA -d $DB_FOLDER -t $TAX_FOLDER`

I hope this helps, let me know if anything is unclear!

Best wishes,

Bastiaan
